name: Ian Czekala #website name
highlighter: rouge
timezone: America/Los_Angeles
encoding: utf-8
work_website: https://iancze.github.io
email: iczekala@stanford.edu
github: iancze
twitter: iczekala
port: 8000
