name: Ian Czekala #website name
markdown: redcarpet
highlighter: pygments
timezone: America/New_York
encoding: utf-8
work_website: http://iancze.github.io
email: iczekala@cfa.harvard.edu
github: iancze
twitter: iczekala
port: 8000
