baseURL: "http://personal.psu.edu/ipc5094/"
languageCode: en-us
title: "Ian Czekala"

theme: "hugo-flex"

params:
  color: black
  summaries: false

  # site-wide custom CSS and JS
  # css:
  #   - css/foo.css
  #   - bar.css
  # js:
  #   - js/foo.js
  #   - bar.js

menu:
  nav:
    - name: About
      url: about/
      weight: 1
    - name: Courses
      url: courses/
      weight: 2
    - name: Tags
      url: tags/
      weight: 3
    - name: Categories
      url: categories/
      weight: 4
