baseURL: "https://iancze.github.io/"
languageCode: en-us
title: "Czekala Group"

theme: "hugo-flex"

googleAnalytics: G-W5586VESJK

params:
  color: black
  width: 48rem
  summaries: false

  # site-wide custom CSS and JS
  css:
    - css/table.css
  #   - bar.css
  # js:
  # - js/ganalytics.js
  #   - bar.js

menu:
  nav:
    - name: People
      url: people/
      weight: 1
    - name: Posts
      url: posts/
      weight: 2
    - name: CV and publications
      url: publications/
      weight: 3
    - name: Courses
      url: courses/
      weight: 4
